name: uw-demo
channels:
  - conda-forge
dependencies:
  - python==3.11
  - compilers
  - pkg-config
  - libxml2
  - cmake
  - swig>=4.0.0
  - ninja
  - pint
  - mpich
  - petsc==3.21.5
  - petsc4py==3.21.5
  - cython=3.*
  - sympy
  - mesalib
  - numpy<2
  - scipy
  - mpi4py
  - h5py=*=mpi*
  - pyvista
  - trame-vtk
  - trame-vuetify
  - pygments
  - typeguard
  - ipywidgets
  - trame
  - gmsh
  - python-gmsh
  - python-xxhash
  - pytest
  - nbmake
  - matplotlib
  - jupyterlab
  - jupytext
  - pip
  - git
  - pip:
    - lavavu
    # - pygmsh
    # - rich<14
    # - meshio
    #- badlands comment out for the following for now
    - "badlands @ git+https://github.com/julesghub/badlands.git@julesghub/meson-build#subdirectory=badlands"
